### ISSUE TITLE
Building straight from template failed.

### ISSUE THREAD

**Issue by bhoov** [GarrettCannon/snowpack-svelte-ts-tw#4]
I get the following error after initializing with the raw template:

```
TypeError: Cannot read property 'length' of undefined
    at sourcemap_add_offset (/Projects/Archive/snowpack-example/node_modules/svelte/compiler.js:22087:23)
    at get_replacement (/Projects/Archive/snowpack-example/node_modules/svelte/compiler.js:28575:10)
    at /Projects/Archive/snowpack-example/node_modules/svelte/compiler.js:28635:21
    at async Promise.all (index 0)
    at async replace_async (/Projects/Archive/snowpack-example/node_modules/svelte/compiler.js:28551:52)
    at async preprocess_tag_content (/Projects/Archive/snowpack-example/node_modules/svelte/compiler.js:28618:22)
    at async Object.preprocess (/Projects/Archive/snowpack-example/node_modules/svelte/compiler.js:28644:10)
    at async Object.load (/Projects/Archive/snowpack-example/node_modules/@snowpack/plugin-svelte/plugin.js:91:11)
    at async runPipelineLoadStep (/Projects/Archive/snowpack-example/node_modules/snowpack/lib/build/build-pipeline.js:45:28)
    at async Object.buildFile (/Projects/Archive/snowpack-example/node_modules/snowpack/lib/build/build-pipeline.js:219:24)
```

Recreate:
```
npx create-snowpack-app snowpack-example --template snowpack-svelte-ts-tw
cd snowpack-example
npm install
npm run build
npm start
```

I have not changed any of the code in the repository. Am I missing something?

**Comment by GarrettCannon** [comment]
That definitely all you should need to do, what version of Node are you using?

**Comment by bhoov** [comment]
v12.14.1

**Comment by shanepadgett** [comment]
I get the exact same error. Node 14.15.1.

**Comment by shanepadgett** [comment]
So I was able to solve this issue by downgrading `svelte-preprocess` to 4.5.2.

**Comment by GarrettCannon** [comment]
I'm going to be looking into this now that I'm back into vacation, it most likely just needs some deps updated

**Comment by GarrettCannon** [comment]
Okay so I pushed a new version to NPM, I think postcss-load-config is what was causing issues a lot of the time, I also bumped some versions and changed the Tailwind build step to be handled by Snowpack which should be faster. I'm going to close this issue, but feel free to reopen or create a new one if the problem persists.
